// Barrel re-export: football game utils
// During migration, all existing imports continue to work unchanged.
// Once imports are updated to use $lib/football/utils/game directly,
// this file can be removed.

export {
	backFns,
	ballPosition,
	beginDisabled,
	calcYardsToGo,
	compareFns,
	descExtraPoint,
	descFieldGoal,
	descKickoff,
	descPenalty,
	descPlay,
	descPunt,
	descSafety,
	descTwoPoint,
	descYardage,
	fieldGoalYardsFns,
	forwardFns,
	getScoreByTeam,
	indexToYards,
	inFieldGoalRange,
	isAutoPlay,
	isAwayBall,
	isFourthDown,
	isGameComplete,
	isHomeBall,
	isModalChoice,
	isOnsideKick,
	isRollAction,
	isTouchback,
	isTouchdown,
	isTouchdownFns,
	kickOffIndexFns,
	lastPlayDesc,
	madeExtraPoint,
	madeFirstDown,
	makeFourthDownChoice,
	makePointChoice,
	primaryColor,
	secondaryColor,
	setFirstDownMarker,
	setRandomTeam,
	showDownDistance,
	teamById,
	teamByUUId,
	togglePossession,
	turnoverOnDowns,
	twoPointSuccess,
	yardsToEndzone,
	yardsToIndex
} from '$lib/football/utils/game';
